### ISSUE TITLE
Open for contribution

### ISSUE THREAD

**Issue by caseymhunt** [chriscoyier/coding-fonts#1]
👋  

I have a particular interest in this project as it feels like I get the urge to "change up my dev font" every few months and I'm never quite satisfied. 

I'd love to contribute by collecting some of the screenshots and/or the micro site. Are you open to contributions? Would you consider doing so for Hacktober?

**Comment by chriscoyier** [comment]
Hey Casey!

That would be awesome to have some help here. This is an idea that's been percolating in my brain for a while. There are lots of lists like this, but making this one into kind of a fun little microsite that anyone can contribute to seems like a way to that it can remain up-to-date for a long time. 

(A fella named Sendil Kumar hit me up about this a few months ago and progressed up until this point, but I haven't heard from him in a while so I just made this repo to pick up the torch and keep it moving. Sendil, if you see this, feel free to contribute here!)

**Here's the important bit that I'd like to try in this repo:**

I wanna see if we can automate the screenshots into a Pupettter (or the like) build process. So you can run it and it creates all the images.

So maybe it's something like:

1. Create a tiny little website server that can serve up the code examples already in this repo (HTML, CSS, JS). 
2. Use something like https://codemirror.com or https://prismjs.com/ to display the code blocks on local URLs
3. Use something like https://github.com/puppeteer/puppeteer/ or https://github.com/microsoft/playwright to visit those URL's and take screenshots of them. 
4. The build process will do the job of swapping out the syntax highlighting themes AND the fonts themselves. 

The awesomeness then is that we have a way to generate the screenshots that will all be entirely sized the same and a fair comparison. 

After we figure that out, then we figure the site out. Probably something simple with like 11ty and Markdown/Frontmatter or something.

**Comment by caseymhunt** [comment]
I like the plan. To get started, I've included Prism as a local lib for now and generated a few code sample pages with syntax highlighting. With these pages in place, a simple web server can serve each of these pages and Puppeteer can generate screenshot(s) at specified viewport for each. I'll try to jam on that next. 

In the meantime, if you're amenable, would you mind flagging the repo appropriately for Hacktoberfest?
![image](https://user-images.githubusercontent.com/2065615/95142379-2ded7880-0739-11eb-9e44-0afdbe8936ca.png)

**Comment by chriscoyier** [comment]
Should be all set there. 

One tricky bit will be the open-source vs. not fonts. I figure it makes sense to put the actual fonts in this repo when we're able to (along with all required licensing) and just don't for the ones that are not. Those will require whoever runs the build process to have the font locally installed for it to work. It would be nice if the build process could somehow detect that and NOT try to take the screenshot if that font is missing.

**Comment by caseymhunt** [comment]
> One tricky bit will be the open-source vs. not fonts. I figure it makes sense to put the actual fonts in this repo when we're able to (along with all required licensing) and just don't for the ones that are not.

💯  agree. I had the same thought. 

> Those will require whoever runs the build process to have the font locally installed for it to work. It would be nice if the build process could somehow detect that and NOT try to take the screenshot if that font is missing.

This may be a case for simple articulated process over complicated automation. We **could** spend time engineering logic and conditionals into when and when not to look for system local vs. repo local font files-- that would save time and energy if we anticipate having to run this process against _all_ font faces regularly. 

I suspect that after the initial payload of fonts have had their screenshots generated, we may rarely, if ever, generate those screenshots again. If this is true, a simpler process for generating screens for 1 font face at a time, may be a more attractive approach. It is likely technically simpler, relies on one-off variables (i.e. where is that font at, repo or system?) instead of complex file searching/logic, and perhaps less volatile. 

Thoughts?

**Comment by caseymhunt** [comment]
For inspiration and possibly for collaboration: https://computecuter.com/

**Comment by chriscoyier** [comment]
I'm down with keeping it simple. Maybe an in-between could be just shooting the screenshots no matter what and if it's missing a font-family, whatever, don't commit that one. 

Or, the script is set up such that you take only one screenshot at a time, like `npm run screenshot ff="Operator Mono" theme="dark" type="HTML"` (or however you do command-line vars)

**Comment by chriscoyier** [comment]
I did a smidge of work here, setting up a npm script to run the screenshots with parameters. Seems to work pretty well. The trick is to alter the script in `package.json` to take the screenshots we need to take, so it's kind of a one-off process instead of presuming to re-take ALL the screenshots at once. Might be worth setting up a re-take all screenshots script though during development, just because if you change one line in a sample file, you kinda gotta re-shoot them all.

**Comment by chriscoyier** [comment]
We can probably close this for more specific issues
