### ISSUE TITLE
HTML/CSS/JS switcher's red thing mis-positioned [bug]

### ISSUE THREAD

**Issue by Steffan153** [chriscoyier/coding-fonts#24]
When you first load the page, if you switch from HTML to CSS/JS, the red thing gets mispositioned like this:
![image](https://user-images.githubusercontent.com/40404519/96502122-9eeb6080-120e-11eb-9a6a-7cb9f37fd48e.png)
Also, if I switch to another font and then back, it fixes itself.

**Comment by landjonathan** [comment]
Hey Steffan,
Would it be possible to get a screenshot of the `div`'s properties in devtools when the issue occurs? Should look something like this:
<img width="1268" alt="Screen Shot 2020-10-19 at 22 33 22" src="https://user-images.githubusercontent.com/43704451/96503045-55753280-125b-11eb-8a61-10d999f11c99.png">

Thanks

**Comment by Steffan153** [comment]
Sure!
![image](https://user-images.githubusercontent.com/40404519/96508974-a0ba2180-1218-11eb-9020-0ff78c93ef1b.png)

**Comment by Steffan153** [comment]
By the way, it works fine in Firefox.

**Comment by landjonathan** [comment]
In which browser does it appear buggy? Does the pink thumb do any transition before stopping at the weird position, or does it just appear there?

**Comment by Steffan153** [comment]
Chrome. It animates normally but it's in the wrong spot.
