### ISSUE TITLE
Screenshots for special characters.

### ISSUE THREAD

**Issue by chriscoyier** [chriscoyier/coding-fonts#26]
I wonder if we could add like a "Special" page in addition to HTML, CSS, and JavaScript. 

Based on some feedback:

> find some way to show zeros vs. O’s, l’s 1's, =>. To me these are some of the key things I want my font to distinguish.

So this bit of code could have that, and other special typographic situations that are worth highlighting. 

This could be the place to draw attention to having or not-having ligatures as well.

**Comment by chriscoyier** [comment]
Whether a font is variable or not is interesting too.

**Comment by this-fifo** [comment]
Thank you for this project, I love the easiness of comparing different fonts! 👏

As far as ligatures, I noticed Hasklig isn't showing ligatures at all which is supposed to be the main sell of that typeface
