### ISSUE TITLE
Serve responsive images

### ISSUE THREAD

**Issue by landjonathan** [chriscoyier/coding-fonts#27]
We need to figure out how best to serve the images.
[Netlify LFS](https://docs.netlify.com/large-media/setup/) looks nice, but would only cover sizes, not formats (which we could also do manually during build). Also, it would require every contributor to install git-lfs, which could be a barrier.
I'm guessing hosted solutions would require a build step to send new images. 
Maybe we need to try this newfangled edge-handler fanciness?

**Comment by chriscoyier** [comment]
I've gone through this same thinking before with other sites. Netlify LFS is nice! But it's a huge barrier to ask every single contributor to get it installed locally (which is non-trivial the one time I did it). 

I think I'd lean toward setting up a Imgix or Cloudinary situation.

**Comment by chriscoyier** [comment]
Done
