### ISSUE TITLE
Images not loading in Brave Mobile

### ISSUE THREAD

**Issue by tskarhed** [chriscoyier/coding-fonts#28]
Images do not load in the Brave mobile browser. When I toggle the shield (regardless of current state) it works.

![Screenshot_20201020-112839.jpg](https://user-images.githubusercontent.com/1438972/96568013-c0f4e980-12c7-11eb-9967-caefa49d1678.jpg)

**Comment by landjonathan** [comment]
I've managed to reproduce this. It seems to solve itself on any change to page settings, whether turning something on or off.
We currently intend to move to external CDN hosting, so perhaps that will resolve the issue. Otherwise, it looks like an interesting bug to submit to Brave.

**Comment by chriscoyier** [comment]
The images are served off Cloudinary on production now. I can't imagine what else we can do here. They are just images yeah? Not sure why they'd be blocked for any reason.
