### ISSUE TITLE
Cloudinary images have strangely long TTFB on AJAX load

### ISSUE THREAD

**Issue by landjonathan** [chriscoyier/coding-fonts#43]
I'm seeing TTFB upwards of 7 seconds. Then all 6 images load at once.
<img width="582" alt="Screen Shot 2020-10-28 at 19 15 05" src="https://user-images.githubusercontent.com/43704451/97471904-e5009c80-1951-11eb-89c3-ceb485d149c1.png">

Seems fine on initial load. Could this be a Cloudinary thing? Very weird.

**Comment by landjonathan** [comment]
From the deploy preview of #44 I can see this helps, but I'm still getting 2-3 second TTFB on some requests.
This is probably worth checking out on the Cloudinary side. I'm pretty sure we were getting better timings from Netlify, but we should check in older deploys.

From a UX perspective, we could add a little spinner to the background of the images' stage. Comparing fonts usually means going back and forth between images that are already cached, so IMO this isn't a very terrible problem. Mostly just weird.

**Comment by chriscoyier** [comment]
My guess is that it's just the fact we're using the "fetch" URL format for Cloudinary, so it has to pull it, transform it, store it, and all that. Once it's done it once, then it's fast. 2-3 seconds is pretty bad though. Maybe a possibility is hitting all these URL's during a deploy build process so no real user has to deal with it. GitHub Actions maybe. 

I'd say it's still probably worth it for performance to have the optimized versions with responsive images on a global CDN and all that, even thought the first-request-ever is pretty rough.

**Comment by landjonathan** [comment]
Yeah, it seems to have resolved itself. Hope that's that.
