### ISSUE TITLE
Go live list?

### ISSUE THREAD

**Issue by chriscoyier** [chriscoyier/coding-fonts#54]
Any words from folks on things they'd want to see before this goes live?

Working on adding the last few fonts from the main list.

**Comment by landjonathan** [comment]
I added a GitHub link to the nav for people who want to contribute (#55).
Other than that I think we're ready to go.

**Comment by chriscoyier** [comment]
Cool cool. I think all I can do is like blog post about it and tweet it and stuff, so I'll do that in the coming days/weeks.
