### ISSUE TITLE
Support lowering the font size

### ISSUE THREAD

**Issue by mkalam-alami** [chriscoyier/coding-fonts#57]
The font size being larger than what I typically use in IDEs, it makes it harder for me to project what in practice would be most comfortable. I tried using the browser zoom but it doesn't behave as expected on Firefox.

A simple control to change the font size would be great :)

Other than that nice job with the website!

**Comment by chriscoyier** [comment]
The fonts are screenshots so it won't be as simple as adjusting font-size. The image in the middle is of fluid width, you can simulate that a bit by changing the browser window size, or opening DevTools and adjusting the parent element size. Unfortunately I'm gonna call taking multiple screenshots at different sizes out of scope for now, but we'll keep this in mind for any design updates. Maybe we can offer a way to resize the image on the fly more easily.
