### ISSUE TITLE
image-rendering may improve image quality on Chromium Browsers

### ISSUE THREAD

**Issue by ricealexander** [chriscoyier/coding-fonts#59]
I'm viewing the site from my Windows desktop from Brave Browser (Chromium).
The images appear slightly blurry.

![code-snippet-default-rendering](https://user-images.githubusercontent.com/18580400/99601473-1571ae80-29c5-11eb-8350-193b1c1e624e.png)

When the following CSS is applied, the image quality is greatly improved.

```css
.screenshot img {
    image-rendering: -webkit-optimize-contrast;
}
```

![code-snippet-optimize-contrast](https://user-images.githubusercontent.com/18580400/99601549-3c2fe500-29c5-11eb-9485-4ec25b0a101a.png)

In Google Chrome, Microsoft Edge, and Brave Browser (all Chromium), applying that CSS greatly improved the quality of the image. In Firefox, the image displayed at a high-quality without any image-rendering changes needed.

**Comment by chriscoyier** [comment]
done
