### ISSUE TITLE
Which Dark and Light theme?

### ISSUE THREAD

**Issue by chriscoyier** [chriscoyier/coding-fonts#6]
https://github.com/PrismJS/prism-themes is a source

Maybe they should look nicely related to each other? Like Material Light / Material Dark?

**Comment by caseymhunt** [comment]
👍 I'm not personally a fan of using Material themes in my editor but in this context, I think the relationship is nice and they both look decent enough on screen.

**Comment by landjonathan** [comment]
I'd also like to try Material Oceanic for the dark one, allowing us to tint the entire site's background to be slightly bluish. The plain gray is a bit drab.

**Comment by chriscoyier** [comment]
Material Light and Materla Oceanic it is!
