### ISSUE TITLE
Recursive is screnshotted with cursive on but upright

### ISSUE THREAD

**Issue by danr** [chriscoyier/coding-fonts#61]
Recursive is screnshotted with cursive on but upright. This is from your webpage's recursive section, look at the `r` and `l`:
![image](https://user-images.githubusercontent.com/199380/99782281-364b1880-2b19-11eb-9ad8-55532a0fa5e3.png)

This is not the default way which mono is written using recursive, which is this:
![image](https://user-images.githubusercontent.com/199380/99782352-4b27ac00-2b19-11eb-86cf-5cdff84396a0.png)

The screenshotted variant on your page is actually this:
![image](https://user-images.githubusercontent.com/199380/99782424-698da780-2b19-11eb-8d9d-052bed61a4ef.png)

If you look at recursive's webpage their intent is that the cursive font is only used for italics, for example here:
![image](https://user-images.githubusercontent.com/199380/99782577-a22d8100-2b19-11eb-98dd-840b8294e90d.png)
https://www.recursive.design/process/

**Comment by chriscoyier** [comment]
Oh great catch, thank you! I'll push an update with corrected settings.
