### ISSUE TITLE
Add The TeX Gyre Cursor / Nova Mono

### ISSUE THREAD

**Issue by lukaszscislowski** [chriscoyier/coding-fonts#80]
@chriscoyier I'd like to add the above fonts to your project. Take a look at them. If you agree, I will create a PR

**Comment by chriscoyier** [comment]
I'm going to pass on both of these. 

https://www.fontsquirrel.com/fonts/tex-gyre-cursor is close but hasn't been touched in 12 years and doesn't seem truly designed for coding.

https://fonts.google.com/specimen/Nova+Mono#standard-styles is way too funky and definitely not designed for coding.

**Comment by lukaszscislowski** [comment]
Okay, I'll come with other ideas
