### ISSUE TITLE
Underscores

### ISSUE THREAD

**Issue by manngo** [chriscoyier/coding-fonts#87]
I haven’t tried all of the fonts, but the fonts which most interested me have the normal width underscore. Originally, of course, this character was used to produce a single underline, while in coding, it’s used as a special character.

__Source Code Pro__ is unusual in that it has a shorter underline character. This way it is easy to read the SQL pattern

	LIKE 'a____'

and count the number of underscores without fiddling with the cursor.

Would it be possible to include a similar string with the other tricky characters?

**Comment by chriscoyier** [comment]
Sounds like a pretty great idea to me! 

Lemme close this and add it to the issue where we're planning the updates to the "Characters" page.
