### ISSUE TITLE
Add a Markdown/Git-based CMS

### ISSUE THREAD

**Issue by chriscoyier** [chriscoyier/coding-fonts#9]
Like

- https://forestry.io/
- https://www.netlifycms.org/
- https://www.stackbit.com/
- https://tinacms.org/

**Comment by landjonathan** [comment]
Are we sure we need a visual CMS? Adding fonts to the repo requires a working knowledge git of node. Can we assume markdown + frontmatter will be manageable for contributors? 
An upside to a tool like this would be enforcing a schema, but I think ours is simple enough that this isn't required.

**Comment by landjonathan** [comment]
I'm a big fan of Netlify CMS, and it would definitely be my recommendation if we decide to implement a visual editor. I'm pretty sure Tina CMS and Stackbit aren't applicable here, unfortunately. No experience with Forestry, and it would be interesting to evaluate.

**Comment by chriscoyier** [comment]
I tried Stackbit Studio but it didn't work for this particular project. I'll just close this for now as it isn't really a bug and we aren't even entirely sure if it's worth doing at all.
