### ISSUE TITLE
Drastically lower image quality on iPad Safari

### ISSUE THREAD

**Issue by johnridesabike** [chriscoyier/coding-fonts#94]
If you visit the site on an iPad, the image quality is *much* lower. It looks very low-res and pixelated. If I visit on my Mac, it looks normal. I haven’t tested on other machines.

I assume this has something to do with the way Cloudinary is serving different sizes and formats to different browsers? 

I attached a screenshot. You can see how the image text looks compared to the actual text on the page.
<img width="768" alt="PNG image" src="https://user-images.githubusercontent.com/37978984/105226768-6f5e3400-5b2e-11eb-9301-069369ff4f8f.png">

**Comment by hronro** [comment]
Not only on iPad, but also on macOS Safari.

<img width="1312" alt="CleanShot 2021-03-16 at 11 16 51@2x" src="https://user-images.githubusercontent.com/15059605/111250920-2ebffa00-8649-11eb-9174-85a27cb10540.png">

OS Version: macOS 11.2.3 (20D91)
Safari Version: Version 14.0.3 (16610.4.3.1.7)

**Comment by chriscoyier** [comment]
I see it too. 

It's something jerked up with the responsive images syntax. If I put like https://res.cloudinary.com/css-tricks/image/fetch/w_1600/https://coding-fonts.css-tricks.com/screenshots/anonymous-pro/html-dark.png as the ONLY thing in srcset, it looks fine. So somehow Safari is deciding to download a far too-small version of the image. 

Any ideas for fixes welcome.

**Comment by eeeps** [comment]
Took a quick first look:

1. It's picking the `1200w` resource when `img.clientWidth` is 840 (@2x). It "should" pick the 1600w for better crispness here, but I think it's just doing what the `sizes` is telling it to. Lemmie workshop your `sizes` for a minute...

2. Ticking this off also helped appearances (chunky → smooth)

<img width="383" alt="Screen Shot 2021-03-25 at 1 34 40 PM" src="https://user-images.githubusercontent.com/3441390/112539969-e0a8a600-8d6e-11eb-9e8c-25120afff3ef.png">

**Comment by eeeps** [comment]
<img width="203" alt="Screen Shot 2021-03-25 at 1 41 59 PM" src="https://user-images.githubusercontent.com/3441390/112540827-e0f57100-8d6f-11eb-90a5-6f2ef4b788f5.png">

Pretty sure those should be `min-width`s.

**Comment by eeeps** [comment]
Gettin' a PR together...

**Comment by eeeps** [comment]
Left the `-webkit-optimize-contrast`, as I see that it was a recent, intentional change (#59).
